"use client"
import { Outfit} from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdatedCartContext } from "./_context/UpdatedCartContext";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";


const inter = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Melikas' Grocery store",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params=usePathname();
  const showheaders=params==="/signin"||params==="/create-account" ?false:true
const [updatedcart, setupdatedcart] = useState(false);
const [cartItems, setCartItems] = useState([]);

const contextValue = {
  updatedcart,
  setupdatedcart,
  cartItems,
  setCartItems
};
  return (
    <PayPalScriptProvider options={{clientId:process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}>
    <html lang="en">
      <body className={inter.className}>
        <UpdatedCartContext.Provider value={contextValue}>
       {showheaders && <Header/>}
        {children}
    <Toaster/>
    </UpdatedCartContext.Provider>
        </body>
    </html>
    </PayPalScriptProvider>
  );
}
