import { Outfit} from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Melikas' Grocery store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
